'use strict';
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const crypto=require('node:crypto');const {LANGUAGES,detect}=require('./language');const {rank}=require('./retrieval');const {classify}=require('./router');const {evaluate}=require('./methodology');const {createGateway}=require('./llm');const {Sessions}=require('./session');const {safeEqual,rateLimiter}=require('./security');const {Analytics}=require('./analytics');const {LearningLibrary}=require('./learning');const {RecognitionStore}=require('./identity');const {detectOpportunity}=require('./opportunity');
const {validate}=require('./validation');
const ROOT=path.resolve(__dirname,'..');
const enquiriesPath=path.join(ROOT,'lara','content','enquiries.jsonl');
function loadDotEnv(){const file=path.join(ROOT,'.env');if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^(['"])(.*)\1$/,'$2');}}
loadDotEnv();
const HOST=process.env.HOST||'127.0.0.1',PORT=Math.max(1,Math.min(Number(process.env.PORT)||4173,65535));
const sessions=new Sessions(Math.max(5,Number(process.env.LARA_SESSION_TTL_MINUTES)||60)*60000);const learning=new LearningLibrary(ROOT);const recognition=new RecognitionStore(ROOT);
const allowRequest=rateLimiter(Math.max(1,Number(process.env.LARA_RATE_LIMIT_PER_MINUTE)||20));const analytics=new Analytics(ROOT);const runtimeConfigPath=path.join(ROOT,'lara/content/runtime-config.json');let runtimeConfig={provider:process.env.LLM_PROVIDER||'none',model:process.env.LLM_MODEL||''};try{runtimeConfig={...runtimeConfig,...JSON.parse(fs.readFileSync(runtimeConfigPath,'utf8'))};}catch{};let gateway=createGateway({...process.env,LLM_PROVIDER:runtimeConfig.provider,LLM_MODEL:runtimeConfig.model});
const indexPath=path.resolve(ROOT,process.env.LARA_INDEX_PATH||'lara/content/knowledge-index.json');const statePath=path.join(ROOT,'lara/content/index-state.json');const disabledPath=path.join(ROOT,'lara/content/disabled-resources.json');
let index=null,disabled=new Set();
function loadIndex(){try{index=JSON.parse(fs.readFileSync(indexPath,'utf8'));}catch{index=null;}try{disabled=new Set(JSON.parse(fs.readFileSync(disabledPath,'utf8')).disabled||[]);}catch{disabled=new Set();}}
loadIndex();
function cookie(req,name){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';}
function setCookie(res,id){res.setHeader('Set-Cookie',`lara_session=${id}; HttpOnly; SameSite=Strict; Path=/_lara; Max-Age=${Math.floor(sessions.ttl/1000)}${process.env.NODE_ENV==='production'?'; Secure':''}`);}
function clearCookie(res){res.setHeader('Set-Cookie','lara_session=; HttpOnly; SameSite=Strict; Path=/_lara; Max-Age=0');}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(data));}
function admin(req){const auth=req.headers.authorization||'';return process.env.LARA_ADMIN_TOKEN&&auth.startsWith('Bearer ')&&safeEqual(auth.slice(7),process.env.LARA_ADMIN_TOKEN);}
function loopback(req){const ip=(req.socket.remoteAddress||'').replace(/^::ffff:/,'');return ['127.0.0.1','::1'].includes(ip);}
async function readBody(req,max){let data='';for await(const part of req){data+=part.toString('utf8');if(Buffer.byteLength(data)>max)throw Object.assign(new Error('Request too large'),{status:413});}try{return JSON.parse(data||'{}');}catch{throw Object.assign(new Error('Invalid JSON'),{status:400});}}
function validOrigin(req){const origin=req.headers.origin;if(!origin)return false;try{return new URL(origin).host===req.headers.host&&['http:','https:'].includes(new URL(origin).protocol);}catch{return false;}}
function excerpts(results,query){const terms=String(query).toLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[];return results.map(({resource})=>{let c=resource.chunks?.[0]?.text||'';let best=0;for(const chunk of resource.chunks||[]){const s=chunk.text.toLowerCase();const score=terms.reduce((n,t)=>n+(s.includes(t)?1:0),0);if(score>best){c=chunk.text;best=score;}}return {resource_id:resource.resource_id,title:resource.title,url:resource.canonical_url,resource_type:resource.resource_type,text:c.slice(0,1800)};});}
function fallbackAnswer(copy,mode,passages,assessment,length){if(mode==='methodology_application'){return `${assessment.status}.\n\n${copy.facts}: ${assessment.user_provided_information.join(' ')}\n\n${copy.used}: ${assessment.relevant_methodologies.length?assessment.relevant_methodologies.join('; '):copy.unknown}\n\n${copy.evidence}\n\n${copy.missing}\n\n${copy.next}`;}
  if(!passages.length)return copy.unknown;
  const p=passages[0];const max=length==='short'?420:length==='detailed'?1200:750;const text=p.text.length>max?p.text.slice(0,max).replace(/\s+\S*$/,'')+'…':p.text;
  const lang=Object.keys(LANGUAGES).find(k=>LANGUAGES[k]===copy)||'en';
  const intro={de:'In den kanonischen OOF-Quellen habe ich diese relevante Passage gefunden:',fr:'J’ai trouvé ce passage pertinent dans les ressources canoniques OOF :',it:'Ho trovato questo passaggio pertinente nelle risorse canoniche OOF:',es:'Encontré este pasaje relevante en los recursos canónicos de OOF:',pt:'Encontrei esta passagem relevante nos recursos canônicos da OOF:',zh:'我在 OOF 权威资源中找到了以下相关内容：',ja:'OOFの正規リソースから、次の関連箇所を見つけました。',ko:'OOF 정본 자료에서 다음 관련 내용을 찾았습니다:',sk:'V kanonických zdrojoch OOF som našiel túto relevantnú pasáž:'}[lang]||'I found this relevant passage in the canonical OOF resources:';
  const canonical={de:'Kanonischer englischer Auszug',fr:'Extrait canonique en anglais',it:'Estratto canonico in inglese',es:'Extracto canónico en inglés',pt:'Trecho canônico em inglês',zh:'英文权威原文摘录',ja:'英語の正規原文からの抜粋',ko:'영어 정본 발췌',sk:'Kanonický anglický úryvok'}[lang]||'Canonical English excerpt';
  return `${intro}\n\n${p.title}\n\n${canonical}:\n${text}\n\n${copy.sources}: ${passages.map(x=>x.title).join('; ')}`;
}
function privateQuery(query){return query.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[email]').replace(/(?<!\w)(?:\+?\d[\d ()-]{7,}\d)(?!\w)/g,'[phone]').replace(/\b(?:sk-[A-Za-z0-9_-]{16,}|gh[pousr]_[A-Za-z0-9_]{16,})\b/g,'[credential]').replace(/\b(password|passwd|secret|api[_ -]?key)\s*[:=]\s*[^\s,;]+/gi,'$1=[redacted]');}
async function chat(req,res){
  const started=Date.now();
  if(!validOrigin(req))return send(res,403,{error:'Same-origin request required'});
  const ip=req.socket.remoteAddress||'unknown';if(!allowRequest(ip))return send(res,429,{error:'Rate limit exceeded'});
  let input;try{input=await readBody(req,Math.max(1000,Number(process.env.LARA_MAX_REQUEST_BYTES)||12000));}catch(e){return send(res,e.status||400,{error:e.message});}
  const question=String(input.question||'').trim();if(!question||question.length>5000)return send(res,400,{error:'Question must contain 1–5000 characters'});
  let sid=cookie(req,'lara_session'),session=sessions.get(sid);if(!session){const created=sessions.create();sid=created.id;session=created.data;setCookie(res,sid);analytics.counts.sessions++;}
  const language=detect(question,input.language||'auto'),copy=LANGUAGES[language]||LANGUAGES.en;const previous=session.messages.filter(m=>m.role==='user').slice(-4).map(m=>m.text);let mode=classify(question,input.mode||'auto');
  if((input.mode||'auto')==='auto'&&previous.length&&session.messages.filter(m=>m.role==='assistant').slice(-1)[0]?.mode==='methodology_application'&&/\b(evidence|gap|next|also|and|it|this|that|dôkaz|medzera|ďalej|preuve|evidencia|证据|証拠|증거)\b/i.test(question))mode='methodology_application';
  const length=['short','standard','detailed'].includes(input.length)?input.length:'standard';const retrievalQuestion=previous.length&&mode==='methodology_application'?[...previous,question].join(' '):question;
  const found=index?rank(index,retrievalQuestion,language,disabled,5):[];const passages=excerpts(found,retrievalQuestion);const assessment=mode==='methodology_application'?evaluate(question,found,language,copy,previous):null;
  const interactionId=crypto.randomUUID();const canonicalLinkRequest=/\b(where (is|can i find)|find|link to|url for|page for|canonical link|show me)\b/i.test(question)||/\b(kde nájdem|nájdi|odkaz na|stránk[au] pre|kde je)\b/i.test(question)||/\b(wo finde|link zu|seite für|où trouver|lien vers)\b/i.test(question);
  let answer=fallbackAnswer(copy,mode,passages,assessment,length),providerState='fallback';
  if(canonicalLinkRequest&&passages.length){answer=`${passages[0].title}\n${passages[0].url}`;providerState='retrieval';}
  else if(gateway.primary&&mode==='knowledge_retrieval'&&passages.length){try{const generated=await gateway.generate({question:privateQuery(question),language:copy.name,mode,length,passages:passages.map(({title,resource_type,text})=>({title,resource_type,text})),assessment:null});const checked=validate(generated,question,passages);if(checked.ok){answer=generated;providerState=runtimeConfig.provider;}else analytics.event('response_rejected',{reason:checked.reason});}catch(error){analytics.counts.provider_errors++;analytics.event('provider_error',{name:error.name,kind:error.kind||'provider_error',message:String(error.message).slice(0,160)});}}
  const opportunity=detectOpportunity(question);if(opportunity&&mode==='methodology_application'&&!canonicalLinkRequest){const next={en:'What outcome are you trying to achieve, and what is the main constraint right now?',sk:'Aký výsledok chcete dosiahnuť a čo je teraz hlavnou prekážkou?',de:'Welches Ergebnis möchten Sie erreichen, und was ist derzeit die größte Einschränkung?',fr:'Quel résultat souhaitez-vous obtenir et quelle est la principale contrainte actuellement?',it:'Quale risultato vuoi ottenere e qual è il principale vincolo?',es:'¿Qué resultado quiere lograr y cuál es la principal limitación?',pt:'Que resultado pretende alcançar e qual é a principal restrição?',zh:'您希望实现什么结果？目前的主要限制是什么？',ja:'どのような成果を目指していますか。現在の主な制約は何ですか。',ko:'어떤 결과를 원하시나요? 현재 가장 큰 제약은 무엇인가요?'};answer+=`\n\n${next[language]||next.en}`;}
  // Persistent learning contains redacted observations with provenance, never raw chat history or canonical edits.
  if(!passages.length&&mode==='knowledge_retrieval')learning.observeGap(question,interactionId);
  if(previous.length&&/\b(that was wrong|you are wrong|incorrect|not correct|doesn't answer|didn't answer|nesprávne|to nie je správne|neodpovedal)\b/i.test(question))learning.record('experience','Visitor indicated that a prior OOF response may need correction',{interactionId,sourceType:'visitor_correction',confidence:0.35,status:'candidate',outcome:'Correction signal observed; canonical claims remain unchanged'});
  // Output uses textContent in the widget. The assessment stays deterministic and evidence-limited.
  const modeLabel=mode==='knowledge_retrieval'?copy.knowledge:copy.assessment;
  const sources=passages.map(({resource_id,title,url,resource_type})=>({resource_id,title,url,resource_type}));
  session.messages.push({role:'user',text:question,language,mode});session.messages.push({role:'assistant',text:answer,language,mode});session.messages=session.messages.slice(-12);
  analytics.query(language,mode,Boolean(passages.length),sources.map(s=>s.title),input.channel==='voice'?'voice':'text',Date.now()-started);
  const machineResponse={status:'ok',answer,objects:sources.map(s=>s.resource_id),canonical_sources:sources,relationships:found.flatMap(({resource})=>resource.related_resources||[]),confidence:passages.length?0.7:0.1,provenance:sources.map(s=>({resource_id:s.resource_id,url:s.url})),error:null};void machineResponse;const result={answer,language,language_name:copy.name,mode,mode_label:modeLabel,sources,trace:input.showTrace&&assessment?assessment.trace:null,provider:providerState,indexed_resources:index?.resource_count||0};
  res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-store','Connection':'keep-alive','X-Content-Type-Options':'nosniff'});
  const delta=18;for(let i=0;i<answer.length;i+=delta){if(res.destroyed)return;res.write(`data: ${JSON.stringify({delta:answer.slice(i,i+delta)})}\n\n`);}
  res.end(`data: ${JSON.stringify({done:result})}\n\n`);
}
function adminHandler(req,res,url){if(!loopback(req))return send(res,403,{error:'Admin routes are available from the server host only'});if(!admin(req))return send(res,401,{error:'Admin authentication required'});
  if(req.method==='GET'&&url.pathname==='/_lara/admin/status'){let state={generated_at:null,changed_pages:[],removed_pages:[]};try{state=JSON.parse(fs.readFileSync(statePath,'utf8'));}catch{};return send(res,200,{indexed_resources:index?.resource_count||0,last_index_date:state.generated_at||null,disabled_count:disabled.size,languages:Object.entries(LANGUAGES).map(([id,v])=>({id,name:v.name})),provider:gateway.primary?`${runtimeConfig.provider} configured`:'Extractive fallback',provider_configuration:{provider:runtimeConfig.provider,model:runtimeConfig.model,configured:Boolean(process.env.LLM_API_KEY)},voice_provider:'Browser speech interfaces',learning_counts:Object.fromEntries(Object.entries(learning.export()).map(([k,v])=>[k,v.length])),analytics:analytics.snapshot(),system_logs:tailLogs(false),error_logs:tailLogs(true)});}
  if(req.method==='GET'&&url.pathname==='/_lara/admin/learning')return send(res,200,{canonical_firewall:'LaRA learning cannot modify canonical OOF content',...learning.export()});
  if(req.method==='GET'&&url.pathname==='/_lara/admin/enquiries'){let records=[];try{records=fs.readFileSync(enquiriesPath,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse);}catch{}return send(res,200,{enquiries:records});}
  if(req.method==='POST'&&url.pathname==='/_lara/admin/learning'){return readBody(req,3000).then(input=>{const type=String(input.type||''),id=String(input.learning_id||''),status=String(input.validation_status||'');if(!['candidate','gap','experience'].includes(type)||!['observed','candidate','reviewed','approved','rejected','active','retired'].includes(status))return send(res,400,{error:'Invalid learning review'});const records=learning.read(type),record=records.find(x=>x.learning_id===id);if(!record)return send(res,404,{error:'Learning record not found'});record.validation_status=status;record.updated_at=new Date().toISOString();record.reviewed_by='authorized_oof_admin';learning.write(type,records);analytics.event('learning_reviewed',{type,learning_id:id,status});return send(res,200,{learning_id:id,validation_status:status,canonical_modified:false});}).catch(()=>send(res,400,{error:'Invalid request'}));}
  if(req.method==='GET'&&url.pathname==='/_lara/admin/settings')return send(res,200,{...runtimeConfig,voice_provider:'browser'});
  if(req.method==='POST'&&url.pathname==='/_lara/admin/settings'){return readBody(req,3000).then(input=>{const selected=String(input.provider||'none');const model=String(input.model||'').trim();if(!['none','openrouter','openai-compatible'].includes(selected))return send(res,400,{error:'Unsupported provider'});if(selected!=='none'&&(!/^[a-zA-Z0-9._/:+-]{1,120}$/.test(model)||!process.env.LLM_API_KEY))return send(res,400,{error:'Set server-side LLM_API_KEY and enter a valid model ID'});runtimeConfig={provider:selected,model:selected==='none'?'':model};fs.writeFileSync(runtimeConfigPath,JSON.stringify(runtimeConfig,null,2),{mode:0o600});gateway=createGateway({...process.env,LLM_PROVIDER:runtimeConfig.provider,LLM_MODEL:runtimeConfig.model});analytics.event('provider_configuration_changed',{provider:selected,model:runtimeConfig.model});return send(res,200,{provider:selected,model:runtimeConfig.model,configured:Boolean(gateway.primary)});}).catch(()=>send(res,400,{error:'Invalid request'}));}
  if(req.method==='GET'&&url.pathname==='/_lara/admin/resources'){const q=(url.searchParams.get('q')||'').toLowerCase();return send(res,200,{resources:(index?.resources||[]).filter(r=>!q||(r.title+' '+r.resource_id).toLowerCase().includes(q)).slice(0,100).map(({resource_id,title,resource_type,architecture,parent_standard,module,canonical_url,related_resources})=>({resource_id,title,resource_type,architecture,parent_standard,module,canonical_url,related_resources,enabled:!disabled.has(resource_id)}))});}
  if(req.method==='POST'&&url.pathname==='/_lara/admin/reindex'){const node=process.execPath,script=path.join(__dirname,'indexing/build-index.js');const result=spawnSync(node,[script],{cwd:ROOT,encoding:'utf8',timeout:120000,windowsHide:true});if(result.status!==0){analytics.event('reindex_error',{code:result.status});return send(res,500,{error:'Index rebuild failed; inspect server logs'});}loadIndex();analytics.event('reindex_complete',{resources:index?.resource_count||0});return send(res,200,{message:result.stdout.trim(),indexed_resources:index?.resource_count||0});}
  if(req.method==='POST'&&url.pathname==='/_lara/admin/resources'){return readBody(req,3000).then(input=>{const id=String(input.resource_id||'');if(!index?.resources.some(r=>r.resource_id===id))return send(res,404,{error:'Resource not found'});if(input.enabled)disabled.delete(id);else disabled.add(id);fs.writeFileSync(disabledPath,JSON.stringify({updated_at:new Date().toISOString(),disabled:[...disabled]},null,2),{mode:0o600});analytics.event('resource_toggle',{resource_id:id,enabled:Boolean(input.enabled)});return send(res,200,{resource_id:id,enabled:!disabled.has(id)});}).catch(()=>send(res,400,{error:'Invalid request'}));}
  return send(res,404,{error:'Not found'});
}
async function submitEnquiry(req,res){if(!validOrigin(req))return send(res,403,{error:'Same-origin request required'});if(!allowRequest(req.socket.remoteAddress||'unknown'))return send(res,429,{error:'Rate limit exceeded'});let input;try{input=await readBody(req,5000);}catch(e){return send(res,e.status||400,{error:e.message});}const email=String(input.email||'').trim(),name=String(input.name||'').trim(),summary=String(input.summary||'').trim();if(input.confirmed!==true)return send(res,400,{error:'Explicit confirmation is required'});if(name.length<1||name.length>100||!/^\S+@\S+\.\S{2,}$/.test(email)||email.length>254||summary.length<10||summary.length>3000)return send(res,400,{error:'Provide a name, valid email and concise request summary'});const record={enquiry_id:crypto.randomUUID(),created_at:new Date().toISOString(),name:name.slice(0,100),organization:String(input.organization||'').trim().slice(0,140),email:email.toLowerCase(),summary:privateQuery(summary).slice(0,3000),requested_next_step:'OOF follow-up requested',status:'received'};try{fs.mkdirSync(path.dirname(enquiriesPath),{recursive:true});fs.appendFileSync(enquiriesPath,JSON.stringify(record)+'\n',{mode:0o600});analytics.event('enquiry_submitted',{enquiry_id:record.enquiry_id});return send(res,201,{enquiry_id:record.enquiry_id,status:'received',email_sent:false,message:'Your enquiry was recorded for OOF follow-up. This server does not send email.'});}catch{analytics.event('enquiry_submission_error');return send(res,500,{error:'Enquiry could not be recorded'});}}
async function identityAction(req,res,action){if(!validOrigin(req))return send(res,403,{error:'Same-origin request required'});if(!allowRequest(req.socket.remoteAddress||'unknown'))return send(res,429,{error:'Rate limit exceeded'});let input;try{input=await readBody(req,2000);}catch(e){return send(res,e.status||400,{error:e.message});}if(action==='create'){const name=String(input.preferred_name||'').trim();if(name.length<1||name.length>60)return send(res,400,{error:'Preferred name must be 1–60 characters'});const canonicalTitles=new Set((index?.resources||[]).map(r=>r.title));const topics=(Array.isArray(input.methodology_topics)?input.methodology_topics:[]).filter(x=>typeof x==='string'&&canonicalTitles.has(x)).slice(-12);const result=recognition.create(name,topics);analytics.event('recognition_passphrase_created');return send(res,201,result);}const result=recognition.restore(input.recognition_passphrase);return result?send(res,200,result):send(res,404,{error:'Recognition passphrase not found'});}
function tailLogs(errors){try{const lines=fs.readFileSync(path.join(ROOT,'lara/content/system-events.jsonl'),'utf8').trim().split(/\r?\n/).filter(Boolean).slice(-40).map(x=>JSON.parse(x));return lines.filter(x=>errors?x.type.includes('error'):!x.type.includes('error')).slice(-20);}catch{return [];}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.txt':'text/plain; charset=utf-8','.woff2':'font/woff2','.pdf':'application/pdf'};
async function serveStatic(req,res,url){if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,{error:'Method not allowed'});let pathname;try{pathname=decodeURIComponent(url.pathname);}catch{return send(res,400,{error:'Bad URL'});}if(pathname==='/')pathname='/index.html';if(pathname==='/lara/admin/'||pathname==='/lara/admin')pathname='/lara/admin/index.html';if(pathname.startsWith('/lara/')&&pathname!=='/lara/admin/index.html')return send(res,404,{error:'Not found'});if(pathname.split('/').some(part=>part.startsWith('.')))return send(res,404,{error:'Not found'});if(['/tests','/tools','/.github','/.git'].some(prefix=>pathname.startsWith(prefix+'/')||pathname===prefix))return send(res,404,{error:'Not found'});const file=path.resolve(ROOT,'.'+pathname);if(!file.startsWith(ROOT+path.sep)&&file!==ROOT)return send(res,403,{error:'Forbidden'});
  if(file.includes(`${path.sep}lara${path.sep}content${path.sep}`)||path.basename(file)==='.env'||file.endsWith('index-state.json')||file.endsWith('system-events.jsonl')||file.endsWith('disabled-resources.json'))return send(res,404,{error:'Not found'});
  let stat;try{stat=fs.statSync(file);if(!stat.isFile())throw 0;}catch{return send(res,404,{error:'Not found'});}const cacheControl=pathname==='/header.js'||path.extname(file).toLowerCase()==='.html'?'no-cache':'public, max-age=300';res.writeHead(200,{'Content-Type':mime[path.extname(file).toLowerCase()]||'application/octet-stream','Content-Length':stat.size,'Cache-Control':cacheControl,'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res);
}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(url.pathname==='/_lara/chat'&&req.method==='POST')return await chat(req,res);if(url.pathname==='/_lara/enquiry'&&req.method==='POST')return await submitEnquiry(req,res);if(url.pathname==='/_lara/identity/create'&&req.method==='POST')return await identityAction(req,res,'create');if(url.pathname==='/_lara/identity/restore'&&req.method==='POST')return await identityAction(req,res,'restore');if(url.pathname.startsWith('/_lara/admin/'))return adminHandler(req,res,url);if(url.pathname==='/_lara/session'&&req.method==='DELETE'){if(!validOrigin(req))return send(res,403,{error:'Same-origin request required'});const id=cookie(req,'lara_session');sessions.clear(id);clearCookie(res);return send(res,200,{ok:true});}return await serveStatic(req,res,url);}catch(error){console.error('[LaRA] request failed:',error.name,String(error.message).slice(0,160));if(!res.headersSent)send(res,500,{error:'LaRA is temporarily unavailable'});else res.end();}});
setInterval(()=>sessions.prune(),60000).unref();server.listen(PORT,HOST,()=>console.log(`LaRA OOF website/backend listening on http://${HOST}:${PORT}; index=${index?.resource_count||0}; provider=${gateway.primary?runtimeConfig.provider:'none'}`));
